name: create executable
on:
  push:
    branches:
      - dev
      - main

jobs:
  create-executable-linux:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'bot-actions-user' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.BOT_PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Linux executable
        run: |
          pyinstaller -y --name linux_runnable src/main.py

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/linux_runnable
          git pull origin ${{ github.ref }}
          git commit -m "Add artifacts" || true

      - name: Push artifacts
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}

  create-executable-windows:
    needs: create-executable-linux
    runs-on: windows-latest
    if: ${{ github.actor != 'bot-actions-user' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.BOT_PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows executable
        run: pyinstaller -y --name windows_runnable src/main.py

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/windows_runnable.exe
          git pull origin ${{ github.ref }}
          git commit -m "Add artifacts" || true

      - name: Push artifacts
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.BOT_PAT_TOKEN }}
