name: create executable
on:
  push:
    branches: 
      - dev
      - main  
jobs:
  create-executable-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      run: |
        if [[ "${{ github.actor }}" == "bot-actions-user" ]]; then
          echo "Skipping workflow execution for BOT."
          exit 0
        fi
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        token: ${{ secrets.BOT_PAT_TOKEN }}

    - name: Set up Python
      run: |
        if [[ "${{ github.actor }}" == "bot-actions-user" ]]; then
          echo "Skipping workflow execution for BOT."
          exit 0
        fi
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        if [[ "${{ github.actor }}" == "bot-actions-user" ]]; then
          echo "Skipping workflow execution for BOT."
          exit 0
        fi
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dependencies
      run: |
        if [[ "${{ github.actor }}" == "bot-actions-user" ]]; then
          echo "Skipping workflow execution for BOT."
          exit 0
        fi
        pip install pyinstaller

    - name: Build Linux executable
      run: |
        if [[ "${{ github.actor }}" == "bot-actions-user" ]]; then
          echo "Skipping workflow execution for BOT."
          exit 0
        fi
        pyinstaller -y --name myscript_linux src/main.py

    - name: Configure Git
      run: |
        if [[ "${{ github.actor }}" == "bot-actions-user" ]]; then
          echo "Skipping workflow execution for BOT."
          exit 0
        fi
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git pull origin ${{ github.ref }}
        git commit -m "Add artifacts" || true
      
    - name: push artifacts
      run: |
        if [[ "${{ github.actor }}" == "bot-actions-user" ]]; then
          echo "Skipping workflow execution for BOT."
          exit 0
        fi
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}

  create-executable-windows:
    needs: create-executable-linux
    runs-on: windows-latest

    steps:
    - name: Check if workflow should be skipped for Bot
      run: |
        if ($env:GITHUB_ACTOR -eq "bot-actions-user") {
          Write-Host "Skipping workflow execution for BOT."
          exit 78
        }
         
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        token: ${{ secrets.BOT_PAT_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build Windows executable
      run: pyinstaller -y --name myscript_windows src/main.py

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git pull origin ${{ github.ref }}
        git commit -m "Add artifacts" || true
    
    - name: push artifacts
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.BOT_PAT_TOKEN }}