name: Docker Image CI

on:
  push:
    branches: [ "pipeline" ]
  pull_request:
    branches: [ "pipeline" ]

jobs:
  # build-and-test:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.9'

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Run tests with coverage
  #       run: |
  #         cd src
  #         coverage run -m unittest

  build-docker-image:
    # needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          username: tommyti
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t tommyti/outil-de-visualisation-evolution-des-traces-execution:latest .

      - name: Push Docker image
        run: docker push tommyti/outil-de-visualisation-evolution-des-traces-execution:latest