name : execute tests and check coverage
on:
    pull_request:
      branches:
        - dev
        - master

jobs:
    build-and-test:
      runs-on: windows-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
  
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
  
        - name: Run tests with coverage
          run: |
            cd src
            coverage run -m unittest || true
  
        - name: Check coverage percentage
          run: |
            cd src
            coverage report --rcfile=.coveragerc --fail-under=80
            if [ $? -eq 0 ] && [ "${{ steps.coverage.outcome }}" == "success" ]; then
              echo "All tests passed and code coverage is >= 80%."
              exit 0
            else
              echo "Some tests failed or code coverage is < 80%."
              exit 1
            fi
    
