name : execute tests and check coverage
on:
    pull_request:
      branches:
        - dev
        - master

jobs:
    build-and-test:
      runs-on: windows-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
  
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
  
        - name: Run tests with coverage
          run: |
            cd src
            coverage run -m unittest
  
        - name: Check coverage percentage
          run: |
            cd src
            coverage report --rcfile=.coveragerc --fail-under=50
